### ISSUE TITLE
kit init erroring out from scratch

### ISSUE THREAD

**Issue by VinSpee** [c8r/kit#194]
Hi! I'm trying out kit for the first time.

the command I'm running:

```sh
❯ yarn kit init
```

the error I'm seeing:

>yarn run v1.7.0
>$ /Users/vincentspeelman/Projects/TED/kit-test/node_modules/.bin/kit >init
> kit  @compositor/kit-cli
>✅  Template: create-react-app
> Select project template
>   next
>   x0
> ❯ create-react-app
>   styled-system
>   rebass
>   tachyons
>   material-ui
> 
> 
> 
> /Users/vincentspeelman/Projects/TED/kit-test/node_modules/ink/lib/h.js:8
>                 throw new TypeError(`Expected component to be a function, but received ${typeof component}. You may have forgotten to export a component.`);
>                 ^
> 
> TypeError: Expected component to be a function, but received undefined. You may have forgotten to export a component.
>     at module.exports.children (/Users/vincentspeelman/Projects/TED/kit-test/node_modules/ink/lib/h.js:8:9)
>     at TextInput.render (/Users/vincentspeelman/Projects/TED/kit-test/node_modules/ink-text-input/dist/index.js:19:10)
>     at TextInput._render (/Users/vincentspeelman/Projects/TED/kit-test/node_modules/ink/lib/component.js:54:15)
>     at mount (/Users/vincentspeelman/Projects/TED/kit-test/node_modules/ink/lib/diff.js:36:35)
>     at diff (/Users/vincentspeelman/Projects/TED/kit-test/node_modules/ink/lib/diff.js:136:3)
>     at diff (/Users/vincentspeelman/Projects/TED/kit-test/node_modules/ink/lib/diff.js:163:21)
>     at diff (/Users/vincentspeelman/Projects/TED/kit-test/node_modules/ink/lib/diff.js:163:21)
>     at diff (/Users/vincentspeelman/Projects/TED/kit-test/node_modules/ink/lib/diff.js:163:21)
>     at build (/Users/vincentspeelman/Projects/TED/kit-test/node_modules/ink/index.js:22:9)
>     at update (/Users/vincentspeelman/Projects/TED/kit-test/node_modules/ink/index.js:55:20)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

any thoughts on what the issue might be? Am I doing something wrong?

**Comment by johno** [comment]
Thanks for opening an issue! Turns out there were conflicting dependencies and I've opened #195 to fix it. Should have a release cut shortly.

**Comment by johno** [comment]
This should now be fixed in v1.0.45. Please let us know if you encounter any other issues.

**Comment by VinSpee** [comment]
All is well. Thank you!
